version: "3.8"

services:
  ftp:
    image: fauria/vsftpd
    container_name: mi-ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER=demo
      - FTP_PASS=demo
      - PASV_ADDRESS=0.0.0.0
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
    volumes:
      - ./almacenamiento:/app/public
    restart: unless-stopped
